services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"

      OVERRIDE_SERVER_PROPERTIES: false
      OVERRIDE_ICON: true

      TYPE: PAPER
      VERSION: 1.21.8
      PAPER_BUILD: 48

      SNOOPER_ENABLED: false

      INIT_MEMORY: 2G
      MAX_MEMORY: 8G

      SERVER_NAME: Mega sej Minecraft server
      MOTD: "&4Mega &1sej &eMinecraft &aServer"
      ICON: /icon.png
      MAX_PLAYERS: 25

      SPAWN_PROTECTION: 0
      DIFFICULTY: hard
      ENABLE_WHITELIST: true
    volumes:
      - ./data:/data
      - ./plugins:/data/plugins
      - ./icon.png:/icon.png

